### ISSUE TITLE
Access expansion policy. Accessing sub problem solution for a given expansion policy

### ISSUE THREAD

**Issue by reganbaucke** [reganbaucke/JuDGE.jl#11]
It would be nice to have some functions that are able to read from the `JuDGEModel` the expansion policy while not necessarily printing it out via `print_expansions`. Further there should be a way to pick out a node, supply a expansion policy to the node, solve the subproblem at the node, and recover the minimisers for the subproblem.

**Comment by adow031** [comment]
I've added some functionality similar to this. In commit f38ddaf5a31a0e927f139ea3cfe44fda2ed93f85 I've added two functions `fix_expansions()` sets the expansions for all subproblems, based on the current solution to the master problem, and `resolve_fixed()` solves each subproblem and computes the overall objective. (This implementation is quite brittle, and only works with JuMParray master variables.)

No function is currently provided to output the subproblem solutions but it is possible to just loop through a model as follows:

`for i=1:m.subprob[m.tree.root].numCols`
    `println(string(Variable(m.subprob[m.tree.root],i)) *": " * string(getvalue(Variable(m.subprob[m.tree.root],i))))`
`end`

It's just a matter of what interface should be provided to the users. Should they specify a node using an array: [1,2,2,1], and a filename, with the solutions printed to that file? Or should they just specify a file, and all the subproblems' solutions get printed to a csv file with the first column being the node, and then the variable name, and then the value?
