### ISSUE TITLE
The coefficients of the expansion variables, and the initial capacity, must be fixed between nodes

### ISSUE THREAD

**Issue by reganbaucke** [reganbaucke/JuDGE.jl#15]
In the knapsack constraint, the coefficients of the expansion variables, and the initial capacity, must be fixed between nodes.

The current interface allows the user to circumvent this requirement of JuDGE.

**Comment by adow031** [comment]
Why is this necessary? I haven't looked at the decomposition for a while, but my belief was that all that is necessary is that the investments relax the problem in some way, leading to lower costs.

**Comment by reganbaucke** [comment]
Yes, but the relaxation must have the same coefficients. In general, we can have node-wise coefficients, but it is an assumption of JuDGE that they remain the same across the tree. We elected to only solve this form of the problem. We can still solve these problems without this assumption, however it greatly increases the difficulty.

The following is a link to the paper by Singh, Philpott and Wood (INFORMS Operations Research, 2009) describing the decomposition:

https://calhoun.nps.edu/bitstream/handle/10945/38417/SinghPhilpottWoodCapacityExpansion.pdf

See Section 4 of this article for the technical explanation.

**Comment by adow031** [comment]
Oh right. The duals would need to be adjusted if the coefficients change. That makes sense.
