### ISSUE TITLE
Expansion variables in objective function

### ISSUE THREAD

**Issue by reganbaucke** [reganbaucke/JuDGE.jl#16]
There is currently no check to ensure that expansion variables do not belong in sub problem constraints. Without this check, the user could specify an illegal JuDGE Model.

**Comment by adow031** [comment]
In JuDGE version 0.5 (1c3324c8eefb8bd925ff1fec6629943be4a3e177) the model validation code was rewritten. It now checks expansion variables appear linearly with the appropriate sign in linear/quadratic inequality constraints; checks are also performed for shutdown variables.

These variables can also appear in the subproblem objective; the use case for this is if an expansion can be 'mothballed' at some cost (either positive or negative) for a given node. The master problem will model the unavoidable costs, and the subproblem handle costs that can be avoided.
