### ISSUE TITLE
Deterministic equivalent

### ISSUE THREAD

**Issue by reganbaucke** [reganbaucke/JuDGE.jl#2]
In the same way that the master problem is automatically generated, we would like to generate a deterministic equivalent JuMP model based off of the definition of the sub-problems. This would allow users to test that "JuDGEsolve" works in the way we expect it to; or even show when JuDGEsolve fails to return a naturally integer solution.

**Comment by adow031** [comment]
This has been added in commit:
https://github.com/reganbaucke/JuDGE.jl/commit/7943188e09ae3fc97a48cb445837845b44af5ad1
