### ISSUE TITLE
Deterministic equivalent model does not accept integer variable types

### ISSUE THREAD

**Issue by calroughan** [reganbaucke/JuDGE.jl#25]
An error is thrown when a MathOptInterface.Integer variable is included in the deteq model. The relevant error reads as:

Building deterministic equivalent problem...ERROR: LoadError: Unsupported constraint type found: MathOptInterface.Integer

**Comment by adow031** [comment]
This has hopefully been fixed with the latest commit: 4a095b4b9b8da328331afb5bc0e3d7e181089ad0

**Comment by calroughan** [comment]
All seems to be working now, thanks
