### ISSUE TITLE
Action timeout

### ISSUE THREAD

**Issue by odow** [reganbaucke/JuDGE.jl#35]
I don't have permission to cancel the existing workflows, but you might want to https://github.com/reganbaucke/JuDGE.jl/actions/workflows/ci.yml

One of the examples is taking ages and not looking like it is going to converge?
![image](https://user-images.githubusercontent.com/8177701/121332740-43700d80-c96c-11eb-81d3-5f0e2b6e6709.png)

Know which one?

**Comment by adow031** [comment]
This was for the cutting-stock problem. I guess it really is experimental. I've updated the set of tests, and now it's all passing.
