### ISSUE TITLE
CodeCoverage

### ISSUE THREAD

**Issue by odow** [reganbaucke/JuDGE.jl#37]
Not sure if @adow031 can turn this on, but try going to https://app.codecov.io/gh/reganbaucke/JuDGE.jl/settings, log-in with your GitHub account, and then see if you can flick a switch to turn on code coverage.

If not, @reganbaucke might have to do it.

**Comment by adow031** [comment]
Appears to be working now...it's at 57%.

I think that's a pass.

**Comment by odow** [comment]
The report is useful to see which parts of the code aren't hit: https://codecov.io/gh/reganbaucke/JuDGE.jl/tree/master/src

Since Julia isn't compiled, it doesn't detect typos in variable names, etc. So coverage really means "it runs and doesn't error" rather than "it's bug-free."
