### ISSUE TITLE
DelimitedFiles fails for CI

### ISSUE THREAD

**Issue by adow031** [reganbaucke/JuDGE.jl#38]
This environment fails when loading DelimitedFiles during the CI, the other two pass.
```
          - version: '1'
            os: ubuntu-latest
            arch: x64
```

**Comment by odow** [comment]
Where?

**Comment by adow031** [comment]
Sorry; It's probably because I just don't have DelimitedFiles in my [targets]. This is needed to test the transportation.jl.

I just couldn't understand why two of the tests passed, and one failed.

[Here's the Github actions CI output.](https://github.com/reganbaucke/JuDGE.jl/runs/2782806357?check_suite_focus=true)
